Add support for MuseScore 4
nozomu-y/MovableDo pull request #5
Opened 2023-12-31 12:25 UTC by pklion

- Closes #4

` README.md ` も併せて変更させていただいたので、よければご確認/修正お願いします。

2024-01-02 07:07 UTC, pklion commented
書きそびれていたのですが、MuseScore 3でも今迄通りの動作をするように下位互換性を保ちつつ変更を加えています。

2024-01-02 07:38 UTC, nozomu-y commented
ありがとうございます！！
手元の MuseScore 4.2.0 で試してみましたが，調性と表記の選択（ComboBox周り）だけ上手く動かないようですね...
QtQuick のバージョンが原因だと思うのでレビュー内容確認していただければと思います！

2024-01-02 07:40 UTC, nozomu-y requested changes

2024-01-02 07:40 UTC, nozomu-y commented on movable-do.qml
```
import QtQuick 2.9
import QtQuick.Controls 2.2
import QtQuick.Layouts 1.1
import QtQuick.Dialogs 1.2
```
手元ではこれで上手く動きました！

2024-01-02 07:44 UTC, nozomu-y commented on movable-do.qml
> +            color: (mscoreMajorVersion < 4? "lightgray" : "#F5F5F6")
```suggestion
            color: (mscoreMajorVersion < 4 ? "lightgray" : "#F5F5F6")
```

2024-01-02 07:44 UTC, nozomu-y commented on movable-do.qml
> +            color: (mscoreMajorVersion < 4? "lightgray" : "#F5F5F6")
細かくて申し訳ないですが...

2024-01-03 05:09 UTC, pklion commented on movable-do.qml
> +            color: (mscoreMajorVersion < 4? "lightgray" : "#F5F5F6")
いえいえ、ありがとうございます
こちらもコード雑に書いてしまったので…すみません

2024-01-03 05:44 UTC, pklion commented on movable-do.qml
ありがとうございます
こちらの環境(Win11)では動作していたので、失念していました。
実は、`QtQuick.Controls` のバージョンによってデザインが大きく異なるので、変更を躊躇っていたところです。
()

## QtQuick.Controls 1.1

![image](https://github.com/nozomu-y/MovableDo/assets/78145811/a74b88d1-babf-439f-a76d-a853b71aa41b) ![image](https://github.com/nozomu-y/MovableDo/assets/78145811/6d2d38f0-ada9-43fa-9352-b6f1a638e7df)

## QtQuick.Controls 2.2

![image](https://github.com/nozomu-y/MovableDo/assets/78145811/7588f2b5-753e-4969-b8a4-90322d647192) ![image](https://github.com/nozomu-y/MovableDo/assets/78145811/b00f0135-32e6-4f90-bf2a-54613e7e0e4c)

`QtQuick.Controls 2.2` では リストが縦に広がらずスクロールする必要があるので(下図)導入しなかったのですが、もし動作しないということでしたら差し替えようと思います。
![image](https://github.com/nozomu-y/MovableDo/assets/78145811/5a0c6430-35cd-4fd8-80d0-e435984ba7ec)

そちら側の状況ももう少し伺っても宜しいでしょうか？
お手を煩わせて申し訳ないです…

2024-01-03 11:33 UTC, nozomu-y commented on movable-do.qml
丁寧に検証していただきありがとうございます！
手元の Mac で QtQuick.Controls 1.1 を使用すると画像のようにドロップダウンが灰色になって選択できないんですよね...
<img width="170" alt="スクリーンショット 2024-01-03 20 24 45" src="https://github.com/nozomu-y/MovableDo/assets/46639706/ee734c3d-b55a-4ff5-a944-fa6f6e2badb2">

色々調べてみたのですが，MuseScore3 と MuseScore4 を両立させて `ComboBox` を使うのは調べた限りできなさそうなので，今回は MuseScore4 用にコードを書き換える方針にするのはいかがでしょうか？ その場合， README には MuseScore3 と MuseScore4 それぞれ分けてインストール方法を記載する必要がありますが...（MuseScore3 用の最新版は `v1.4` で MuseScore4 用の最新版は `v2.0` にしようと思っています

そしてリストが縦に広がらない現象は Mac でも確認できました．この問題は`QtQuick.Controls` の代わりに `MuseScore.UiComponents` を使うことで解消できそうなので，手元で上手く動いた方法をレビューに残しますね！

2024-01-03 11:46 UTC, nozomu-y commented on movable-do.qml
>  import MuseScore 3.0
```suggestion
import MuseScore 3.0
import MuseScore.UiComponents 1.0
```

2024-01-03 11:46 UTC, nozomu-y commented on movable-do.qml
> +
```suggestion
    id: root

```

2024-01-03 11:46 UTC, nozomu-y commented on movable-do.qml
> +
```suggestion

    property int tonalityIndex: -1
    property int notationIndex: -1

```

2024-01-03 11:46 UTC, nozomu-y commented on movable-do.qml
> +
そして， `ComboBox` 周りのコードには↑のように差分を提案できなかったのでコメントに残しますね．

```diff
- ComboBox {
+ StyledDropdown {
      id: tonality
      model: [
          "C-Dur", "G-Dur", "D-Dur", "A-Dur", "E-Dur", "H-Dur", "Fis-Dur", "Cis-Dur", "F-Dur", "B-Dur", "Es-Dur", "As-Dur", "Des-Dur", "Ges-Dur", "Ces-Dur",
          "a-moll", "e-moll", "h-moll", "fis-moll", "cis-moll", "gis-moll", "dis-moll", "ais-moll", "d-moll", "g-moll", "c-moll", "f-moll", "b-moll", "es-moll", "as-moll"
      ]
+     currentIndex: root.tonalityIndex
+     onActivated: function(index) {
+         root.tonalityIndex = index
+     }
  }
```

「表記」の方も同様ですね

Mac では動きましたが， Windows では検証できていないので，検証できて問題なかったら反映のほどよろしくお願いいたします！

2024-01-03 11:54 UTC, nozomu-y commented
ここまでのレビュー内容を反映させた Mac での見た目がこんな感じですね．
MuseScore3 までの時とは異なり調性は全ては表示されていませんが， `ComboBox` を使ったときよりはスクロールが少なくてすみそうです．

<img width="643" alt="スクリーンショット 2024-01-03 20 49 11" src="https://github.com/nozomu-y/MovableDo/assets/46639706/16ee14f8-fe06-4ece-9bea-4b824fd10ab7">
<img width="295" alt="スクリーンショット 2024-01-03 20 49 31" src="https://github.com/nozomu-y/MovableDo/assets/46639706/4b8c6c6e-d9cb-447e-bc10-85284ca005f2">

2024-01-04 12:57 UTC, pklion commented
いただいたレビューについては1番目のコミットで、`ComboBox`については2番目のコミットで変更いたしました。
`UiComponents`、使い方が分からなかったのでありがたいです

併せて

-  `QtQuick 2.9` と `QtQuick.Controls 2.2` に変更
- UIの観点から`Button`を`UiComponents`の`FlatButton`に変更
- `master`ブランチで`Qt.quit()`になっている部分を、`return`ではなく後継である`quit()`に変更
(MuseScore3での互換性が必要なくなったため)

させていただきました。

![image](https://github.com/nozomu-y/MovableDo/assets/78145811/b26cdd5f-564d-470c-9a86-55ba82512bc6)

2024-01-04 13:02 UTC, pklion commented on movable-do.qml
なるほど、ありがとうございます。
もし宜しければ #3 で`master`に取り込まれた内容が`v1.4`に入っていないので、MuseScore3用に`v1.5`を出すか`v2.0`に2種類添付するかの形でリリースして頂けると嬉しいです。

2024-01-05 05:53 UTC, nozomu-y commented
#3 の内容を v1.5 としてリリースしました！（リリース忘れていてすみません...ご指摘ありがとうございます！）

2024-01-05 05:57 UTC, nozomu-y commented
`FlatButton` への変更，`quit()` への変更とても助かります！ありがとうございます！！
README の変更は v2.0 のリリースと合わせて行なってしまいますね！

コードは問題なく動いているのを確認できたのでこのままマージしてしまします．
PR ありがとうございました！

2024-01-05 05:57 UTC, merged

2024-01-05 06:52 UTC, pklion commented
@nozomu-y ありがとうございました！
いつも使わせていただいているので、お役に立てて光栄です。